/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/denuncias": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Submete uma denúncia com anexos opcionais
         * @description Envelope multipart contendo o objeto `Complaint` como JSON no campo
         *     `denuncia` e 0..N anexos como `arquivo_1..N` (documentos) e opcionalmente
         *     `arquivo_audio` (gravação).
         */
        post: operations["submeterDenuncia"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/municipios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lista municípios por UF */
        get: operations["listarMunicipios"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Complaint: {
            /**
             * @description Canal de entrada da denúncia
             * @enum {string}
             */
            origem: "WEB" | "WHATSAPP_BOT";
            irregularidades: components["schemas"]["Irregularidade"][];
            relato_texto?: string;
            relato_audio_transcricao?: string;
            /** @enum {string} */
            relato_audio_transcricao_status?: "NAO_APLICAVEL" | "PENDENTE" | "CONCLUIDA" | "FALHA" | "EDITADA_MANUALMENTE";
            /** @enum {string} */
            numero_prejudicados?: "UM" | "DOIS_A_CINCO" | "SEIS_A_VINTE" | "VINTE_UM_A_CEM" | "MAIS_DE_CEM";
            /** @enum {string} */
            modalidade_trabalho?: "PRESENCIAL" | "REMOTO" | "HIBRIDO" | "INFORMAL" | "TERCEIRIZADO" | "OUTRA";
            grupos_vulneraveis?: ("IDOSO" | "CRIANCA" | "PESSOA_COM_DEFICIENCIA" | "OUTRO")[];
            /** @enum {string} */
            tipo_identificacao: "ANONIMO" | "IDENTIFICADO";
            /** @description Omitido quando tipo_identificacao=ANONIMO */
            nome_completo?: string;
            /**
             * Format: email
             * @description Omitido quando tipo_identificacao=ANONIMO
             */
            email?: string;
            /** @description Omitido quando tipo_identificacao=ANONIMO */
            telefone?: string;
            uf: string;
            municipio: string;
            /** @description Código IBGE do município */
            municipio_ibge?: string;
            nome_empresa?: string;
            endereco_empresa?: string;
            testemunhas?: components["schemas"]["Testemunha"][];
            /** @description Obrigatório true para submeter */
            consentimento_lgpd?: boolean;
        };
        Irregularidade: {
            /** @description Ex. FALTA_EPI, ASSEDIO, ATRASO_SALARIO */
            codigo: string;
            rotulo?: string;
            icone?: string;
            categoria?: string;
        };
        Testemunha: {
            tem_testemunhas: boolean;
            nome_referencial?: string;
            contato_opcional?: string;
        };
        Municipio: {
            codigo_ibge: string;
            nome: string;
            uf: string;
        };
        DenunciaAceita: {
            /** @description Prefixo SYN- no MVP (mock). Formato real do MPT em DEC-DN-19. */
            protocolo: string;
            /** Format: date-time */
            timestamp: string;
            classificacao?: components["schemas"]["Classificacao"];
        };
        /**
         * @description Classificação automática do relato. Prioridade é sempre setada
         *     server-side (R-DN-02). Alertas URGENTE exigem revisão humana (R-DN-03).
         */
        Classificacao: {
            categoria?: string;
            subcategoria?: string;
            /** @enum {string} */
            prioridade?: "BAIXA" | "MEDIA" | "ALTA" | "URGENTE";
            /** @enum {string} */
            metodo?: "REGRA_DETERMINISTICA" | "MODELO_ML";
            versao_classificador?: string;
            revisada_por_humano?: boolean;
        };
        ErroApi: {
            /** @description Código de erro estável (para i18n do cliente) */
            codigo: string;
            mensagem: string;
            detalhes?: {
                [key: string]: unknown;
            };
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    submeterDenuncia: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** @description JSON serializado do objeto Complaint */
                    denuncia: string;
                    /** Format: binary */
                    arquivo_1?: string;
                    /** Format: binary */
                    arquivo_2?: string;
                    /** Format: binary */
                    arquivo_3?: string;
                    /** Format: binary */
                    arquivo_audio?: string;
                };
            };
        };
        responses: {
            /** @description Denúncia aceita */
            201: {
                headers: {
                    /** @description Identificador de correlação */
                    "X-Request-ID"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DenunciaAceita"];
                };
            };
            /** @description Validação falhou */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroApi"];
                };
            };
            /** @description Tamanho excedido */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroApi"];
                };
            };
            /** @description Antimalware ou MIME rejeitado */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroApi"];
                };
            };
            /** @description Rate limit excedido */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroApi"];
                };
            };
        };
    };
    listarMunicipios: {
        parameters: {
            query: {
                uf: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lista de municípios */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Municipio"][];
                };
            };
            /** @description UF inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErroApi"];
                };
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Serviço saudável */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "ok";
                        /** Format: date-time */
                        timestamp?: string;
                        version?: string;
                    };
                };
            };
        };
    };
}
